name: Streamlit Code Check

on:
  push:
    branches: [ "master" ]

jobs:
  test-pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Training Script to Verify Model Creation
      run: |
        python train.py
        test -f model/regression_model.pkl # Verify model was created
